import {
  AdminUser,
  CatalogTrack,
  DistributionContract,
  Distributor,
  PaymentTransaction,
  ReviewAction,
  ReviewRequest,
  ServicePackage,
  SongLicense,
  SystemAuditLog,
  UserDevice,
} from "./types";

export const INITIAL_USERS: AdminUser[] = [
  {
    id: 1,
    fullName: "Nguyễn Văn Listener",
    username: "listener01",
    email: "listener@moodify.local",
    phone: "0901000001",
    role: "USER",
    status: "ACTIVE",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240",
    artistSpotifyId: null,
    staffCode: null,
    devicesCount: 2,
    lastLoginAt: "15/09/2026 08:10",
    createdAt: "01/01/2026",
  },
  {
    id: 2,
    fullName: "Trần Minh Artist",
    username: "artist01",
    email: "artist@moodify.local",
    phone: "0901000002",
    role: "ARTIST",
    status: "ACTIVE",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=240",
    artistSpotifyId: "4OCl7UfKRXLcYouOYa3Bwc",
    staffCode: null,
    devicesCount: 2,
    lastLoginAt: "15/09/2026 08:00",
    createdAt: "01/02/2026",
  },
  {
    id: 3,
    fullName: "Lê Hoàng Moderator",
    username: "moderator01",
    email: "moderator@moodify.local",
    phone: "0901000003",
    role: "MODERATOR",
    status: "ACTIVE",
    avatarUrl: null,
    artistSpotifyId: null,
    staffCode: "MOD-VN-009",
    devicesCount: 1,
    lastLoginAt: "15/09/2026 07:45",
    createdAt: "01/03/2026",
  },
  {
    id: 4,
    fullName: "Phạm Quốc Admin",
    username: "admin01",
    email: "admin@moodify.local",
    phone: "0901000004",
    role: "ADMIN",
    status: "ACTIVE",
    avatarUrl: null,
    artistSpotifyId: null,
    staffCode: "ADM-ROOT-001",
    devicesCount: 3,
    lastLoginAt: "18/09/2026 10:15",
    createdAt: "15/01/2026",
  },
  {
    id: 5,
    fullName: "Hoàng Anh Banned",
    username: "banned01",
    email: "banned@moodify.local",
    phone: "0901000005",
    role: "USER",
    status: "BANNED",
    avatarUrl: null,
    artistSpotifyId: null,
    staffCode: null,
    banReason: "Phát hiện hành vi gian lận lượt stream và bình luận xúc phạm cộng đồng",
    bannedUntil: "Vĩnh viễn",
    devicesCount: 1,
    lastLoginAt: "10/09/2026 14:00",
    createdAt: "01/04/2026",
  },
  {
    id: 6,
    fullName: "Vũ Hải Đăng",
    username: "haidang_music",
    email: "haidang@soundwave.io",
    phone: "0901000006",
    role: "ARTIST",
    status: "ACTIVE",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=240",
    artistSpotifyId: "5K4W6rqAhSsszDTafWSA5R",
    staffCode: null,
    devicesCount: 1,
    lastLoginAt: "17/09/2026 21:30",
    createdAt: "12/04/2026",
  },
  {
    id: 7,
    fullName: "Ngô Mai Phương",
    username: "phuongmaingo",
    email: "phuong.ngo@gmail.com",
    phone: "0901000007",
    role: "USER",
    status: "INACTIVE",
    avatarUrl: null,
    artistSpotifyId: null,
    staffCode: null,
    devicesCount: 0,
    lastLoginAt: null,
    createdAt: "14/09/2026",
  },
];

export const INITIAL_DEVICES: UserDevice[] = [
  {
    id: 1,
    userId: 1,
    deviceUuid: "android-user1-phone-001",
    platform: "ANDROID",
    deviceName: "Samsung Galaxy S24 Ultra",
    status: "ACTIVE",
    createdAt: "01/05/2026 08:00",
  },
  {
    id: 2,
    userId: 1,
    deviceUuid: "ios-user1-phone-002",
    platform: "IOS",
    deviceName: "iPhone 15 Pro Max",
    status: "ACTIVE",
    createdAt: "01/06/2026 08:00",
  },
  {
    id: 3,
    userId: 2,
    deviceUuid: "android-artist-phone-003",
    platform: "ANDROID",
    deviceName: "Google Pixel 9 Pro",
    status: "ACTIVE",
    createdAt: "01/07/2026 08:00",
  },
  {
    id: 4,
    userId: 2,
    deviceUuid: "other-artist-device-004",
    platform: "OTHER",
    deviceName: "iPad Pro M4 (Studio Controller)",
    status: "REVOKED",
    createdAt: "15/05/2026 08:00",
  },
  {
    id: 5,
    userId: 5,
    deviceUuid: "android-banned-phone-005",
    platform: "ANDROID",
    deviceName: "Xiaomi 14 Ultra",
    status: "REVOKED",
    createdAt: "01/08/2026 08:00",
  },
];

export const INITIAL_REVIEWS: ReviewRequest[] = [
  {
    id: 1,
    artistUserId: 2,
    artistName: "Trần Minh (Teeme)",
    contentType: "TRACK",
    contentId: "6a8230b53cccfc45cd626d10",
    title: "Chạm Khẽ Giọt Nắng",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400",
    genre: "Lo-fi Indie / Pop",
    requestType: "PUBLISH",
    status: "PENDING",
    submittedAt: "17/09/2026 14:20",
    resolvedAt: null,
    audioUrl: "https://musiccollector.kandes.io.vn/data/audio/xesi-hoaprox/3b2kCFZhX9GYnQ58qL1cAM_vo-tinh.mp3",
    lyricsPlain: "Từng giọt nắng khẽ rơi bên hiên nhà vắng...\nEm đi qua để lại chút hương thu...",
    audioFeatures: {
      bpm: 85,
      energy: 0.48,
      danceability: 0.62,
      valence: 0.55,
      acousticness: 0.78,
      keySignature: "C Major",
    },
  },
  {
    id: 2,
    artistUserId: 6,
    artistName: "Vũ Hải Đăng",
    contentType: "TRACK",
    contentId: "6a8230b53cccfc45cd626d11",
    title: "Midnight Resonance (Remix)",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400",
    genre: "Progressive House / EDM",
    requestType: "UPDATE",
    status: "IN_REVIEW",
    submittedAt: "16/09/2026 09:15",
    resolvedAt: null,
    audioUrl: "https://musiccollector.kandes.io.vn/data/audio/bts/7zwuoHtRMNpXlhVdmnPFB8_dynamite.mp3",
    lyricsPlain: "Feel the frequency, riding through the night...\nBassline moving electric lights...",
    audioFeatures: {
      bpm: 128,
      energy: 0.88,
      danceability: 0.82,
      valence: 0.74,
      acousticness: 0.12,
      keySignature: "F# Minor",
    },
  },
  {
    id: 3,
    artistUserId: 2,
    artistName: "Trần Minh (Teeme)",
    contentType: "ALBUM",
    contentId: "8c8230b53cccfc45cd626010",
    title: "Neon Horizon - Extended EP",
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400",
    genre: "Synthwave / Cyberpop",
    requestType: "PUBLISH",
    status: "APPROVED",
    submittedAt: "10/09/2026 08:00",
    resolvedAt: "11/09/2026 10:00",
  },
  {
    id: 4,
    artistUserId: 2,
    artistName: "Trần Minh (Teeme)",
    contentType: "TRACK",
    contentId: "6a8230b53cccfc45cd626d12",
    title: "Vỡ Vụn (Acoustic Demo)",
    coverUrl: "https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?w=400",
    genre: "Acoustic Ballad",
    requestType: "PUBLISH",
    status: "REJECTED",
    submittedAt: "09/09/2026 08:00",
    resolvedAt: "10/09/2026 15:00",
    lyricsPlain: "Lời hứa xưa nay tan vào hư vô...\nMưa rơi ướt lối về...",
    audioFeatures: {
      bpm: 72,
      energy: 0.28,
      danceability: 0.40,
      valence: 0.22,
      acousticness: 0.92,
      keySignature: "A Minor",
    },
  },
];

export const INITIAL_REVIEW_ACTIONS: ReviewAction[] = [
  {
    id: 1,
    reviewRequestId: 2,
    moderatorUserId: 3,
    moderatorName: "Lê Hoàng Moderator",
    action: "START_REVIEW",
    reason: "Bắt đầu kiểm tra ca từ và chứng nhận bản phối gốc",
    createdAt: "16/09/2026 10:00",
  },
  {
    id: 2,
    reviewRequestId: 3,
    moderatorUserId: 3,
    moderatorName: "Lê Hoàng Moderator",
    action: "APPROVE",
    reason: "Nội dung chất lượng cao, đầy đủ bản quyền và đạt chuẩn âm thanh WAV 24-bit.",
    createdAt: "11/09/2026 10:00",
  },
  {
    id: 3,
    reviewRequestId: 4,
    moderatorUserId: 3,
    moderatorName: "Lê Hoàng Moderator",
    action: "RETURN_FOR_EDIT",
    reason: "Ảnh bìa chứa watermark không chính chủ, yêu cầu tải lên ảnh chất lượng tối thiểu 1400x1400px.",
    createdAt: "09/09/2026 12:00",
  },
  {
    id: 4,
    reviewRequestId: 4,
    moderatorUserId: 3,
    moderatorName: "Lê Hoàng Moderator",
    action: "REJECT",
    reason: "Bản phối vi phạm bản quyền giai điệu từ tác phẩm đã đăng ký sở hữu trí tuệ.",
    createdAt: "10/09/2026 15:00",
  },
];

export const INITIAL_TRACKS: CatalogTrack[] = [
  {
    id: "6a8230b53cccfc45cd626ced",
    spotifyId: "track_tinhve_001",
    title: "TÌNH VỀ NƠI ĐÂU",
    artist: "Teeme, Hoaprox",
    album: "TINH VE Album",
    genre: "Electronic / Chillstep",
    vibeCategory: "Chill",
    duration: "03:45",
    coverUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300",
    audioUrl: "https://musiccollector.kandes.io.vn/data/audio/teeme/0nVlY4IVVIY4gr7FKreThp_tinh-ve.mp3",
    plays: 338390,
    likes: 18400,
    status: "published",
    moderationScore: 0.98,
    bpm: 110,
    energy: 0.65,
    danceability: 0.72,
    valence: 0.60,
    acousticness: 0.35,
    keySignature: "D Minor",
    createdAt: "01/08/2026",
  },
  {
    id: "6a8230b53cccfc45cd626cee",
    spotifyId: "track_neon_pulse_002",
    title: "Neon Pulse Skyline",
    artist: "Hoaprox, K-391",
    album: "Future Cyber Bass",
    genre: "EDM / Melodic Dubstep",
    vibeCategory: "Energetic",
    duration: "04:12",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300",
    audioUrl: "https://musiccollector.kandes.io.vn/data/audio/mochiii-domino/5cY01Gpd3FrBbgGmOtSsyW_canh-hoa-heo-tan-domino-remix.mp3",
    plays: 240000,
    likes: 14200,
    status: "published",
    moderationScore: 0.95,
    bpm: 140,
    energy: 0.92,
    danceability: 0.78,
    valence: 0.85,
    acousticness: 0.08,
    keySignature: "G Major",
    createdAt: "10/08/2026",
  },
  {
    id: "6a8230b53cccfc45cd626cef",
    spotifyId: "track_rainy_memory_003",
    title: "Ký Ức Cơn Mưa Chiều",
    artist: "Trần Minh Artist",
    album: "Mùa Mưa Tháng Bảy",
    genre: "Lo-Fi / Indie Sadness",
    vibeCategory: "Sadness",
    duration: "03:15",
    coverUrl: "https://images.unsplash.com/photo-1445985543470-41fdd6ce388d?w=300",
    audioUrl: "https://musiccollector.kandes.io.vn/data/audio/xesi-hoaprox/3b2kCFZhX9GYnQ58qL1cAM_vo-tinh.mp3",
    plays: 150000,
    likes: 9800,
    status: "published",
    moderationScore: 0.99,
    bpm: 78,
    energy: 0.32,
    danceability: 0.50,
    valence: 0.28,
    acousticness: 0.85,
    keySignature: "F Minor",
    createdAt: "15/08/2026",
  },
  {
    id: "6a8230b53cccfc45cd626cf0",
    spotifyId: "track_deep_focus_004",
    title: "Deep Space Ambient Coding",
    artist: "Moodify AI Sound Lab",
    album: "Study & Work Frequency",
    genre: "Ambient / Instrumental",
    vibeCategory: "Focus",
    duration: "05:30",
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300",
    audioUrl: "https://musiccollector.kandes.io.vn/data/audio/buitruonglinh/5G9kwWUmTzgKMAsbwwPiPC_thinh-vuong-viet-nam-sang-ngoi.mp3",
    plays: 180000,
    likes: 11500,
    status: "published",
    moderationScore: 1.0,
    bpm: 60,
    energy: 0.20,
    danceability: 0.25,
    valence: 0.45,
    acousticness: 0.65,
    keySignature: "C Major",
    createdAt: "20/08/2026",
  },
  {
    id: "6a8230b53cccfc45cd626cf1",
    spotifyId: "track_summer_sunset_005",
    title: "Hoàng Hôn Sau Đồi Cỏ",
    artist: "Vũ Hải Đăng",
    album: "Những Mùa Đi Qua",
    genre: "Acoustic Pop / Romance",
    vibeCategory: "Romance",
    duration: "03:52",
    coverUrl: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=300",
    audioUrl: "https://musiccollector.kandes.io.vn/data/audio/noah/56RZrGkLlgQzD1tvZDTU2j_thiep-hong.mp3",
    plays: 120000,
    likes: 8300,
    status: "published",
    moderationScore: 0.94,
    bpm: 95,
    energy: 0.58,
    danceability: 0.64,
    valence: 0.82,
    acousticness: 0.72,
    keySignature: "E Major",
    createdAt: "28/08/2026",
  },
];

export const INITIAL_PACKAGES: ServicePackage[] = [
  {
    id: 1,
    name: "Moodify Trial 7 Days",
    description: "Gói dùng thử miễn phí không giới hạn kho nhạc Lossless trong 7 ngày đầu.",
    price: 0,
    durationDays: 7,
    displayOrder: 1,
    status: "ACTIVE",
  },
  {
    id: 2,
    name: "Premium 30 Days",
    description: "Nghe nhạc không quảng cáo, tải offline 3 thiết bị, chất lượng 320kbps & FLAC.",
    price: 59000,
    durationDays: 30,
    displayOrder: 2,
    status: "ACTIVE",
  },
  {
    id: 3,
    name: "Premium 90 Days",
    description: "Tiết kiệm 15% so với gói tháng. Đầy đủ quyền lợi Premium và huy hiệu VIP.",
    price: 149000,
    durationDays: 90,
    displayOrder: 3,
    status: "ACTIVE",
  },
  {
    id: 4,
    name: "Artist Pro 365 Days",
    description: "Dành riêng cho Nghệ sĩ: Đăng tải bài hát không giới hạn, phân tích dữ liệu chuyên sâu.",
    price: 599000,
    durationDays: 365,
    displayOrder: 4,
    status: "ACTIVE",
  },
  {
    id: 5,
    name: "Legacy 45 Days",
    description: "Gói khuyến mãi tri ân đã ngừng tiếp nhận lượt đăng ký mới.",
    price: 99000,
    durationDays: 45,
    displayOrder: 5,
    status: "INACTIVE",
  },
];

export const INITIAL_TRANSACTIONS: PaymentTransaction[] = [
  {
    id: 1,
    subscriptionId: 2,
    userName: "Nguyễn Văn Listener",
    userEmail: "listener@moodify.local",
    packageName: "Premium 90 Days",
    amount: 149000,
    paymentMethod: "EWALLET",
    provider: "MOMO",
    providerTransactionId: "MOMO-20260901-00001",
    status: "SUCCESS",
    paidAt: "01/09/2026 00:02",
  },
  {
    id: 2,
    subscriptionId: 1,
    userName: "Nguyễn Văn Listener",
    userEmail: "listener@moodify.local",
    packageName: "Premium 30 Days",
    amount: 59000,
    paymentMethod: "QR_PAY",
    provider: "VNPAY",
    providerTransactionId: "VNPAY-20260915-00012",
    status: "PENDING",
    paidAt: "15/09/2026 09:55",
  },
  {
    id: 3,
    subscriptionId: 3,
    userName: "Trần Minh Artist",
    userEmail: "artist@moodify.local",
    packageName: "Artist Pro 365 Days",
    amount: 599000,
    paymentMethod: "CREDIT_CARD",
    provider: "VNPAY",
    providerTransactionId: "VNPAY-20250101-00003",
    status: "FAILED",
    paidAt: "01/01/2026 10:01",
  },
  {
    id: 4,
    subscriptionId: 4,
    userName: "Trần Minh Artist",
    userEmail: "artist@moodify.local",
    packageName: "Premium 30 Days",
    amount: 59000,
    paymentMethod: "EWALLET",
    provider: "MOMO",
    providerTransactionId: "MOMO-20260801-00004",
    status: "CANCELLED",
    paidAt: "01/08/2026 10:05",
  },
  {
    id: 5,
    subscriptionId: 5,
    userName: "Hoàng Anh Banned",
    userEmail: "banned@moodify.local",
    packageName: "Premium 30 Days",
    amount: 59000,
    paymentMethod: "CREDIT_CARD",
    provider: "VNPAY",
    providerTransactionId: "VNPAY-20260901-00005",
    status: "REFUNDED",
    paidAt: "10/09/2026 15:00",
  },
];

export const INITIAL_DISTRIBUTORS: Distributor[] = [
  {
    id: 1,
    companyName: "Universal Music Vietnam",
    country: "Vietnam",
    contactName: "Nguyễn Quốc Anh",
    contactEmail: "umg.contact@universalmusic.vn",
    contactPhone: "02830000001",
    status: "ACTIVE",
    contractCount: 3,
  },
  {
    id: 2,
    companyName: "Believe Digital Vietnam",
    country: "Vietnam",
    contactName: "Trần Minh Đức",
    contactEmail: "duc.tran@believe.com",
    contactPhone: "02830000002",
    status: "ACTIVE",
    contractCount: 2,
  },
  {
    id: 3,
    companyName: "Independent Distribution Co.",
    country: "Singapore",
    contactName: "Lê Hoàng Nam",
    contactEmail: "nam.le@indiedist.sg",
    contactPhone: "02830000003",
    status: "INACTIVE",
    contractCount: 1,
  },
  {
    id: 4,
    companyName: "Global Sound Distribution",
    country: "United States",
    contactName: "Phạm Quang Huy",
    contactEmail: "huy.pham@globalsound.us",
    contactPhone: "02830000005",
    status: "ACTIVE",
    contractCount: 1,
  },
];

export const INITIAL_CONTRACTS: DistributionContract[] = [
  {
    id: 1,
    distributorId: 1,
    distributorName: "Universal Music Vietnam",
    contractCode: "DIST-2026-001",
    title: "Hợp đồng phân phối nhạc số Universal 2026",
    signedDate: "01/01/2026",
    effectiveFrom: "01/01/2026",
    effectiveTo: "31/12/2026",
    revenueShare: 70.0,
    status: "ACTIVE",
    documentUrl: "https://moodify.vn/docs/contracts/DIST-2026-001.pdf",
  },
  {
    id: 2,
    distributorId: 2,
    distributorName: "Believe Digital Vietnam",
    contractCode: "DIST-2026-002",
    title: "Hợp đồng đối tác Indie Streaming 2026",
    signedDate: "01/08/2026",
    effectiveFrom: "01/09/2026",
    effectiveTo: "31/08/2027",
    revenueShare: 65.0,
    status: "ACTIVE",
    documentUrl: "https://moodify.vn/docs/contracts/DIST-2026-002.pdf",
  },
  {
    id: 3,
    distributorId: 3,
    distributorName: "Independent Distribution Co.",
    contractCode: "DIST-2025-003",
    title: "Hợp đồng phân phối tổng hợp 2025",
    signedDate: "01/01/2025",
    effectiveFrom: "01/01/2025",
    effectiveTo: "31/12/2025",
    revenueShare: 60.0,
    status: "EXPIRED",
    documentUrl: "https://moodify.vn/docs/contracts/DIST-2025-003.pdf",
  },
];

export const INITIAL_LICENSES: SongLicense[] = [
  {
    id: 1,
    trackId: "6a8230b53cccfc45cd626ced",
    trackTitle: "TÌNH VỀ NƠI ĐÂU",
    distributorName: "Universal Music Vietnam",
    licenseType: "DIGITAL_STREAMING",
    copyrightOwner: "Universal Music Publishing Group",
    issueDate: "01/01/2026",
    expiryDate: "31/12/2026",
    status: "ACTIVE",
  },
  {
    id: 2,
    trackId: "6a8230b53cccfc45cd626cee",
    trackTitle: "Neon Pulse Skyline",
    distributorName: "Believe Digital Vietnam",
    licenseType: "MASTER_LICENSE",
    copyrightOwner: "Believe Digital & Hoaprox Entertainment",
    issueDate: "10/08/2026",
    expiryDate: "10/08/2027",
    status: "ACTIVE",
  },
  {
    id: 3,
    trackId: "6a8230b53cccfc45cd626cef",
    trackTitle: "Ký Ức Cơn Mưa Chiều",
    distributorName: "Independent Direct",
    licenseType: "DIRECT_LICENSE",
    copyrightOwner: "Trần Minh (Nghệ sĩ độc lập)",
    issueDate: "15/08/2026",
    expiryDate: "15/08/2028",
    status: "ACTIVE",
  },
];

export const INITIAL_AUDIT_LOGS: SystemAuditLog[] = [
  {
    id: "log-1",
    timestamp: "18/09/2026 10:15:30",
    operatorName: "Phạm Quốc Admin",
    operatorRole: "ADMIN",
    category: "IAM",
    action: "BAN_USER",
    target: "banned01 (Hoàng Anh)",
    details: "Khóa vĩnh viễn tài khoản do phát hiện chạy bot gian lận lượt stream.",
    severity: "critical",
  },
  {
    id: "log-2",
    timestamp: "17/09/2026 16:40:12",
    operatorName: "Phạm Quốc Admin",
    operatorRole: "ADMIN",
    category: "SYSTEM",
    action: "UPDATE_AI_THRESHOLD",
    target: "AI Emotion Engine",
    details: "Điều chỉnh ngưỡng độ tin cậy Emotion Confidence từ 0.70 lên 0.75.",
    severity: "info",
  },
  {
    id: "log-3",
    timestamp: "16/09/2026 14:25:00",
    operatorName: "Lê Hoàng Moderator",
    operatorRole: "MODERATOR",
    category: "MODERATION",
    action: "APPROVE_RELEASE",
    target: "Neon Horizon - Extended EP",
    details: "Duyệt xuất bản Album gồm 5 bài hát cho nghệ sĩ Trần Minh.",
    severity: "info",
  },
  {
    id: "log-4",
    timestamp: "15/09/2026 09:10:45",
    operatorName: "Phạm Quốc Admin",
    operatorRole: "ADMIN",
    category: "BILLING",
    action: "PROCESS_REFUND",
    target: "TXN: VNPAY-20260901-00005",
    details: "Hoàn tiền 59.000 VNĐ cho tài khoản vi phạm đã bị vô hiệu hóa.",
    severity: "warning",
  },
];
